trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  displayName: Retrieve version from pom.xml
  inputs:
    script: |
      v=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo "##vso[task.setvariable variable=FrederickVersion;]$v"

- task: Maven@3
  displayName: Maven package
  inputs:
    mavenPomFile: 'pom.xml'
    options: '--no-transfer-progress'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: 'target/site/jacoco/jacoco.xml'
    pathToSources: 'src/main/java'
    failIfCoverageEmpty: true

- task: CopyFiles@2
  displayName: Copy Frederick.cmd
  inputs:
    SourceFolder: 'install'
    Contents: 'Frederick.cmd'
    TargetFolder: '$(Build.BinariesDirectory)'

- task: CopyFiles@2
  displayName: Copy binaries
  inputs:
    SourceFolder: 'target'
    Contents: 'Frederick.jar'
    TargetFolder: '$(Build.BinariesDirectory)/lib'

- task: CmdLine@2
  displayName: Inject jre
  inputs:
    script: |
      wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jre_x64_windows_hotspot_17.0.5_8.zip
      unzip OpenJDK17U-jre_x64_windows_hotspot_17.0.5_8.zip -d $(Build.BinariesDirectory)
      mv $(Build.BinariesDirectory)/jdk-17.0.5+8-jre $(Build.BinariesDirectory)/jre

- task: ArchiveFiles@2
  displayName: Zip binaries
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Frederick-$(FrederickVersion).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish binaries
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'