name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    #SET v=(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) && \
    - name: Retrieve Version
      run: |
        SET v=TEMP-VERSION
        echo "PROJECT_VERSION=%v%" >> $env:GITHUB_ENV

    - name: Maven package site
      run: mvn -B package site --no-transfer-progress --file pom.xml

    - name: Stage binaries
      run: |
        mkdir staging
        cp install/Frederick.cmd staging/Frederick.cmd
        cp target/generated-sources/license/THIRD-PARTY.txt staging/third-party.txt
        cp target/generated-sources/license/LICENSE.txt staging/license.txt
        mv target/dependency staging/lib
        mv target/generated-resources/licenses staging/lic
        mv target/site staging/doc
        unzip target/frederick.zip -d staging/jre

    - name: Zip files
      run: |
        mkdir artefact && \
        (cd staging && zip -q -r ../artefact/Frederick-${{env.PROJECT_VERSION}}.zip .)

    - name: Publish build
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: artefact/*.zip

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
